# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json package-lock.json ./
RUN npm install --ignore-scripts

# Bundle app source
COPY . .

# Build the app
RUN npm run build

# Expose any required ports (if necessary, not specified here)

# Run the server
CMD [ "node", "build/index.js" ]
